eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka:password@localhost:8761/eureka
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
    health:
        circuitbreakers:
            enabled: true


#Resilience4j Properties

resilience4j.circuitbreaker:
    instances:
        inventory:
            registerHealthIndicator: true
            event-consumer-buffer-size: 10
            slidingWindowType: COUNT_BASED
            slidingWindowSize: 5
            failureRateThreshold: 50
            waitDurationInOpenState: 5s
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true

#Resilience4j Timeout Properties
resilience4j.timelimiter:
    instances:
        inventory:
            timeoutDuration: 3s
            cancelRunningFuture: true

#Resilience4j Retry Properties

resilience4j.retry:
    instances:
        inventory:
            max-attempts: 3
            wait-duration: 5s

    zipkin:
        base-url: http://locallhost:9411


# Trace every action
    tracing:
        sampling:
            probability:1.0

server:
    port: 8081
spring:
    application:
        name: order-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: claveMYSQL
        url: jdbc:mysql://localhost:3306/order_service
        username: root
    jpa:
        hibernate:
            ddl-auto: update


    #Kafka Properties
    kafka:
        bootstrap-servers: localhost:9092
        template:
            default-topic: notificationTopic
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring:
                    json:
                        type:
                            mapping: event:com.project.orderservice.event.OrderPlacedEvent
